# Generated by Django 5.0.3 on 2024-04-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchandise', '0002_marchandisepost_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchandisepost',
            name='photo',
        ),
        migrations.AddField(
            model_name='marchandisepost',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
