# Generated by Django 5.0.3 on 2024-03-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='image',
        ),
    ]
