# Generated by Django 5.0.3 on 2024-04-17 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_salon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
