# Generated by Django 5.0.3 on 2024-04-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='productpost',
        ),
    ]
