# Generated by Django 5.0.3 on 2024-04-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('publish_blogpost', 'Can publish a BlogPost')]},
        ),
    ]
