# Generated by Django 5.0.3 on 2024-05-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_author_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Type_salon',
            field=models.CharField(choices=[('Mixte', 'Mixte'), ('Homme', 'Homme'), ('Femme', 'Femme')], default='Mixte', max_length=10),
            preserve_default=False,
        ),
    ]
