# Generated by Django 5.0.3 on 2024-05-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_salon_delete_person_remove_blogpost_type_salon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
