# Generated by Django 5.0.3 on 2024-05-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_salonevaluation_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonevaluation',
            old_name='rating',
            new_name='etoiles',
        ),
    ]
