# Generated by Django 5.0.3 on 2024-05-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
